### ISSUE TITLE
Trash Readme

### ISSUE THREAD

**Issue by ShubhamVidhate** [akshat2602/akshat2602#1]
Trash readme. Nothing ben
[Psycho (1).pdf](https://github.com/akshat2602/akshat2602/files/10167769/Psycho.1.pdf)
efisial. Aise readme bich to me bhi desarv nahi karta

**Comment by ShubhamVidhate** [comment]
> Trash readme. Nothing ben [Psycho (1).pdf](https://github.com/akshat2602/akshat2602/files/10167769/Psycho.1.pdf) efisial. Aise readme bich to me bhi desarv nahi karta

Fix this asap

**Comment by akshat2602** [comment]
Yes, done
